### ISSUE TITLE
Deserialization of FormDesignType XML does not use correct default value for ListFieldType maxSelections

### ISSUE THREAD

**Issue by SachaFyson** [IHE-SDC-WG/SDC-Framework#7]
I don't know if repository is still being worked on, but here goes.

When calling the FormDesignType.DeserializeFromXmlPath method on a valid Form Design File (FDF), the value of the maxSelections property of any ListFieldType without that XML attribute should be 1, per the specification in the SDC Technical Reference Guide. This would make the ListFieldTypes single-select by default.

However, when the method is called, the value of maxSelections is 0 if it is not specified in the FDF. This will cause the ListFieldType to become multi-select. You can reproduce this by deserializing an FDF that contains single-select ListFieldTypes and reserializing it. The resulting ListFieldTypes will now have the property maxSelections=0.

**Comment by cap-rmoldwi** [comment]
@SachaFyson Thanks, I will look into this.
